### ISSUE TITLE
Retro Tere

### ISSUE THREAD

**Issue by BarbaraBravoRedondo** [Adalab/project-promo-u-module-2-team-6#20]

**Comment by mteresacastro** [comment]
**A MEJORAR

- Tomarse sus tiempos de descanso.
- Frustarse menos, y tomar las cosas con mas tranquilidad.
- Mejorar en maquetación (footer).

**A DESTACAR 

- Proactiva.
- Meticulosa y perfeccionista.
- Flexible pese a las circunstancias.
