### ISSUE TITLE
Retro Yasmin

### ISSUE THREAD

**Issue by BarbaraBravoRedondo** [Adalab/project-promo-u-module-2-team-6#21]

**Comment by mteresacastro** [comment]
**A MEJORAR

- Maquetación (solventar pequeños detalles).
- Algún problema técnico aislado.
- Más participativa en las reuniones grupales.

**A DESTACAR 

- Buen trabajo individual, y toma de referencias y recursos.
- Actitud positiva, buenas soft skills para trabajar en grupo y comunicación asertiva.
- Creativa y buenas ideas.
